# Сайт. Используется в PWA и Django
HOST=sova.online

# orgName используется в заголовках окон Login, Signup
orgName = Sova.online


# readonly
DEMO_MODE = 


# Django. Обязательно введите свой SECRET_KEY не менее 50 символов !!!
DEBUG = 1
SECRET_KEY = H9LyyJw0_9Cs(j_u14-rtscw6@m387%f1(#fooe5=e*g@!aqw-#_zftb7c_x-iv&
addAllowedHosts = localhost, 127.0.0.1, 192.168.0.110

# Home page
HOME_PAGE = /api/opendoc?dbAlias=draft&page=home-page
# HOME_PAGE = /api/login/


# smtp
DEVELOPMENT_MODE = 
DEFAULT_FROM_EMAIL = info@sova.online
EMAIL_HOST = smtp.go1.unisender.ru
EMAIL_PORT = 587
EMAIL_USE_TLS = 1
EMAIL_HOST_USER = 5961271
EMAIL_HOST_PASSWORD = 6zfwttxcbemtf969x7wpkaoku38qr8bad8x5tq8a



# for Yandex-disk:
Y_OAuthToken = 
serviceName = Sova.online




# for vk:
# токен администратора получить по ссылке https://vkhost.github.io/
vk_adm_token = 
# id нашего приложения oAuth2
vk_app_id=
# Защищённый ключ нашего приложения (client_secret)
vk_client_secret=
# Сервисный ключ доступа нашего приложения (токен доступа)
vk_app_token=
# Группа для преподавателей, которые будут загружать видеофайлы (доступ по записи)
vk_group_id = 
# id юзера, который получил токен администратора
vk_user_id = 




