orgName = Новый Век
organisation = ООО "Новый Век"

SECRET_KEY = django-insecure-i^ign@v#a)uvrer1exq9a*^xm&7wtrwt%8se6zlm^=g8lt(mk8

# for Yandex-disk:
Y_OAuthToken = y0_AgAAAABpC_Z2AADLWwAAAAESSzVkAACa4NPwtF1B1pcbdEkPRWVKusZvCA
serviceName = Новый век



# for vk: токен администратора получить по ссылке https://vkhost.github.io/
vk_adm_token = vk1.a.EtNapPM5V7PQv0C-wKTlzPSZqdCSN1hcvGI_gNE8Qx3-DzytfvPwOhPcvOxjoLdcgOEvQOtFYHO5ZZMyAjZof2YNw_gdfZrjgLOOHJGsTEZVDt-sfjfjPGq_ZWlfwEX1GOeVAbJPFKjFWKAf3bfAkT6iJ5mOidDBgUcOz1n9k39xq2qkehDR4HiVxRqfP1DQTT7h8Z_6KTFB2KQ4_QsvlQ


# id нашего приложения oAuth2
vk_app_id=51845645 

# Защищённый ключ нашего приложения (client_secret)
vk_client_secret=WWSJ4rpqISYsGT9GDTiC

# Сервисный ключ доступа нашего приложения (токен доступа)
vk_app_token=f1d064a6f1d064a6f1d064a63cf2c77eabff1d0f1d064a694699fc1a7996e4d6ef01162

# Группа для преподавателей, которые будут загружать видеофайлы (доступ по записи)
vk_group_id = 227993416

# id юзера, который получил токен администратора
vk_user_id = 79624421

# HOME_PAGE = /api/opendoc?dbAlias=draft&mode=read&key_key=homePage
HOME_PAGE = /api/login/



