# Сайт. Используется в PWA и Django
HOST=sova.online

# orgName используется в заголовках окон Login, Signup
orgName = Sova.online
organisation = ООО "Результат"


# кнпка "наш сайт содержит куки"
coocieBtn = 1

# readonly
DEMO_MODE = 

# директория с базами sqlite
DB_DIR = 


# Django. Обязательно введите свой SECRET_KEY не менее 50 символов !!!
DEBUG = 
SECRET_KEY = (*B^&s(j_u14-rtscw6@m387%f1(#fooe5=e*g@!aqw-#_zftb7><+#$%HF&*78
addAllowedHosts = localhost, 127.0.0.1

# Home page
HOME_PAGE = /api/opendoc?dbAlias=draft&page=home-page&manifest=1


# smtp
DEVELOPMENT_MODE = 
DEFAULT_FROM_EMAIL = info@sova.online
EMAIL_HOST = 
EMAIL_PORT = 587
EMAIL_USE_TLS = 1
EMAIL_HOST_USER = 
EMAIL_HOST_PASSWORD = 



# for Yandex-disk:
Y_OAuthToken = 
serviceName = 




# for vk:
# токен администратора получить по ссылке https://vkhost.github.io/
vk_adm_token = 
# id нашего приложения oAuth2
vk_app_id=
# Защищённый ключ нашего приложения (client_secret)
vk_client_secret=
# Сервисный ключ доступа нашего приложения (токен доступа)
vk_app_token=
# Группа для преподавателей, которые будут загружать видеофайлы (доступ по записи)
vk_group_id =
# id юзера, который получил токен администратора
vk_user_id = 

