# Generated by Django 4.2.9 on 2024-07-02 05:21

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True, verbose_name='Состояние')),
                ('body', models.TextField(blank=True, null=True)),
            ],
            managers=[
                ('docs', django.db.models.manager.Manager()),
            ],
        ),
    ]
