# Generated by Django 4.2.9 on 2024-07-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nv_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='starting_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
